// Proyecto-en-Angular/src/app/componentes/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core';

//Servicios
import { ProductosService } from '../../servicios/productos.service';
import { CarritoService } from '../../servicios/carrito.service';

@Component({
  selector: 'app-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})
export class CarritoComponent implements OnInit {

  //Variables

  pedidos = [];
  productos:any = [];
  total = 0;

  constructor(private productosService:ProductosService, private carritoService:CarritoService) { 
  }

  ngOnInit(): void {
    this.productosService.datosProductos().subscribe((datos) => {
      this.productos = datos;
    });

    this.pedidos = this.pedidos.concat(this.carritoService.pedido);
    this.total += this.carritoService.total;
  }

  cancelarCompra(){
    this.pedidos = [];
    this.total = 0;
    this.carritoService.borrarCarrito();
  }

  pagarProductos(){
    this.pedidos = [];
    this.total = 0;
    this.carritoService.borrarCarrito();
  }

}

<div class="contenedor">
    <div class="header">
        <h1>Carrito de compras</h1>
    </div>

    <div class="carrito">
        <div class="productos">
            <div *ngFor="let pedido of pedidos" class="producto">
                <img src="../../../assets/img/{{productos[pedido.id].img}}.jpg" alt="{{productos[pedido.id].img}}" title="{{productos[pedido.id].img}}">
                <div class="info-producto">
                    <p>{{productos[pedido.id].nombre}}</p>
                    <p>Unidades: {{pedido.numero}}</p>
                    <p>Subtotal: ${{pedido.numero * productos[pedido.id].precio}}</p>
                </div>
            </div>
        </div>
        <div class="info-pago">
            <p>Total: ${{total}}</p>
            <div class="botones">
                <button (click)="cancelarCompra()">Cancelar</button>
                <button (click)="pagarProductos()">Pagar</button>
            </div>
        </div>
    </div>
</div>

// proyecto-en-react/src/components/carrito/carrito.js
import React from 'react';
import './carrito.css';

//Imagenes
import aguacate from '../../img/aguacate.jpg';
import ajo from '../../img/ajo.jpg';
import almendras from '../../img/almendras.jpg';
import arandanos from '../../img/arandanos.jpg';
import lychee from '../../img/lychee.jpg';
import calabza from '../../img/calabaza.jpg';
import canela from '../../img/canela.jpg';
import fresa from '../../img/fresa.jpg';
import kiwi from '../../img/kiwi.jpg';
import limon from '../../img/limon.jpg';
import maiz from '../../img/maiz.jpg';
import manzana from '../../img/manzana.jpg';
import papa from '../../img/papa.jpg';
import pasta from '../../img/pasta.jpg';
import pimienta from '../../img/pimienta.jpg';
import repollo from '../../img/repollo.jpg';
import zanahoria from '../../img/zanahoria.jpg';
import tomate from '../../img/tomate.jpg';

//JSON
import productosJSON from '../../productos.json';


export default class App extends React.Component{

    state = {
        prodcutos: productosJSON
    }
    pedidos = [];
    pedidos = this.props.pedidos;

    imagenes = [
        aguacate,ajo,almendras,arandanos,lychee,calabza,canela,fresa,kiwi,limon,maiz,manzana,papa,pasta,pimienta,repollo,zanahoria,tomate
    ]

    render(){
        return (
            <div className="contenedor-carrito">
                <div className="header-carrito">
                    <h1>Carrito de compras</h1>
                </div>

                <div className="carrito-carrito">
                    <div className="productos-carrito">
                        {this.pedidos.map(e =>
                            <div className="producto-carrito" key={e.id}>
                                <img src={this.imagenes[e.id]} alt={this.state.prodcutos[e.id].img} title={this.state.prodcutos[e.id].img}/>
                                <div className="info-producto-carrito">
                                    <p>{this.state.prodcutos[e.id].nombre}</p>
                                    <p>Unidades: {e.numero}</p>
                                    <p>Subtotal: ${e.id * this.state.prodcutos[e.id].precio}</p>
                                </div>
                            </div>
                        )}
                    </div>
                    <div className="info-pago-carrito">
                        <p>Total: $</p>
                        <div className="botones-carrito">
                            <button>Cancelar</button>
                            <button>Pagar</button>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
