// Proyecto-en-Angular/src/app/componentes/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router'

//Servicios
import { LoginService } from '../../servicios/login.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  //Variables

  url = '../../../assets/login.json' ;
  datosLogin: any = {};

  errorCorreo: string;
  errorContrasena: string;

  constructor(private loginservice:LoginService, private router:Router) {
      this.loginservice.datosLogin(this.url).subscribe((datos) => {
      this.datosLogin = datos;
    })
   }

  ngOnInit(): void {
  }

  validarDatos(correo, contrasena){
    if(correo == '' || contrasena == ''){
      if(contrasena != ''){
        this.errorCorreo = '...campo vacio';
        this.errorContrasena = '';
      }else if(correo != ''){
        this.errorCorreo = '';
        this.errorContrasena = '...campo vacio';
      }else{
        this.errorCorreo = '';
        this.errorContrasena = '';
      }
    }else{
      if(correo != this.datosLogin.correo || contrasena != this.datosLogin.contrasena){
        if(correo == this.datosLogin.correo){
          this.errorCorreo = '';
          this.errorContrasena = '...los datos no coinciden';
        }else{
          this.errorCorreo = '...los datos no coinciden';
          this.errorContrasena = '';
        }
      }else{
        this.errorCorreo = '';
        this.errorContrasena = '';
        this.router.navigate(['tienda']);
      }
    }
  }

}

<div class="contenedor">
    <div class="formulario">
        <h1>Iniciar Sesión</h1>
        <form>
            <label for="correo">Correo electrónico <span>{{errorCorreo}}</span></label>
            <input type="email" id="correo" #correo/>
            <label for="contrasena">Contraseña <span>{{errorContrasena}}</span></label>
            <input type="password" id="contrasena" #contrasena/>
        </form>
        <button (click) = 'validarDatos(correo.value, contrasena.value)'>Ingresar</button>
    </div>
</div>

// proyecto-en-react/src/components/login/login.js
import React from 'react';
import LoginJSON from "../../login.json";
import './login.css';

import App from '../../App';

export default class Login extends React.Component {

  //Variables
  errorCorreo = '';
  errorContrasena = '';

  constructor(props){
    super(props);
    this.state = {
      email: '',
      password:'' 
    }
  }

  obtenerEmail(email){
    this.setState({
      email: email
    });
  }

  obtenerPassword(password){
    this.setState({
      password: password
    });
  }

  enviarDatos = (e) =>{
    let state = this.state;
    if(state.email == LoginJSON.correo && state.password == LoginJSON.contrasena){
     this.props.onClick(); 
    }
  }

  render(){

    return (
      <div className="contenedor-login">
        <div className="formulario-login">
           <h1>Iniciar Sesión</h1>
           <form>
            <label htmlFor="correo">Correo electrónico <span>{this.errorCorreo}</span></label>
             <input
               onChange={(event)=>{ this.obtenerEmail(event.target.value)}} 
               type="email" 
               value={this.state.email}
               id="correo"
               required
               />
             <label htmlFor="contrasena">Contraseña <span>{this.errorContrasena}</span></label>
             <input
              onChange={(event)=>{ this.obtenerPassword(event.target.value)}} 
              type="password" 
              value={this.state.password}
              id="contrasena"
              required
              />
              <div className="boton-ingresar-login">
                <input
                  onClick={ this.enviarDatos }
                  type="submit"
                  value="Ingresar"
                />
              </div>
           </form>
         </div>
       </div>
     );
  }
}
